<? // theme defaults file
	// this file contains defaults for text color, hiliting, etc etc etc
	
$_theme_colors = array(
	"gray"=>array(
			"bg"=>					"gray",
			"bgcolor" =>			"CCCCCC",
			"a"=>					"990000",
			"tag01"=>				"998888",
			"tag02"=>				"996666",
			"tag03"=>				"993333",
			"a:hover"=>				"990000",
			"text"=>				"444",
			"font-size"=>			"12px",
			"input-borders"=>		"555",
			"input-size"=>			"12px",
			"box-color"=>			"CCCCCC",
			"box-border-color"=>	"CCCCCC",
			"btnlink-color"=>		"d33",
			"btnlink-border-color"=>"d55",
			"title-color"=>			"000000",
			"title-under-color"=>	"000000",
			"th-color"=>			"777",
			"th-background"=>		"e9e9e9",
			"td-color"=>			"333",
			"td0"=>					"F8F8F8",
			"td1"=>					"E0E0E0",
			"header"=>				"fff",
			"nav"=>					"990000",
			"navtext"=>				"FFFFFF",
			"contentarea"=>			"fff",
			"borders"=>				"444",
			"contentinfo"=>			"999"
	),
	"blue"=>array(
			"bg"=>					"blue",
			"bgcolor" =>			"003366",
			"a"=>					"990000",
			"tag01"=>				"993333",
			"a:hover"=>				"990000",
			"text"=>				"444",
			"font-size"=>			"12px",
			"input-borders"=>		"555",
			"input-size"=>			"12px",
			"box-color"=>			"efefef",
			"box-border-color"=>	"999",
			"btnlink-color"=>		"d33",
			"btnlink-border-color"=>"d55",
			"title-color"=>			"aaa",
			"title-under-color"=>	"aaa",
			"th-color"=>			"777",
			"th-background"=>		"e9e9e9",
			"td-color"=>			"333",
			"td0"=>					"D8D8D8",
			"td1"=>					"F8F8F8",
			"header"=>				"fff",
			"nav"=>					"FFCC00",
			"navtext"=>				"FFFFFF",
			"contentarea"=>			"fff",
			"borders"=>				"444",
			"contentinfo"=>			"999"
	)
);
