<?	// this file contains an array of descriptions for the site creation templates

$descriptions = array (
	"template0"=>"A basic site with explanations, good for getting started with a personal site."
	,"template3"=>"A basic course site with pages for <i>Course Description</i>, <i>Syllabus</i> and information about the instructor."
	,"template2"=>"A site set up for use as a personal or group weblog."
	,"template1"=>"A course site with predefined sections for <i>Introduction</i>, <i>Assignments</i>, <i>Discussions</i>, a <i>Blog</i> and <i>Presentations</i>."
	,"template4"=>"Useful for quick start to sites."
	,"template5"=>"Blank site for starting from scratch."
);