<?	// this file contains an array of descriptions for the site creation templates

$descriptions = array (
	"template0"=>"An almost blank site, good for getting started with a personal site."
	,"template3"=>"A basic course site with sections for <i>Course Description</i> and <i>Syllabus</i>."
	,"template2"=>"A course site with predefined sections for <i>Introduction</i>, <i>Assignments</i>, <i>Syllabus</i>, and <i>Links</i>."
	,"template1"=>"Similar to the standard course site, but adds a section for <i>Discussions</i>."
);